app.benchmark.enabled=true
app.benchmark.squadre=30
app.benchmark.giocatori-per-squadra=15
app.benchmark.warmup=3
app.benchmark.ripetizioni=10
app.benchmark.output-directory=benchmark-results

spring.jpa.properties.hibernate.generate_statistics=true

spring.jpa.open-in-view=false

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.stat=warn
